//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationTool.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Engine
    {
        public Engine()
        {
            this.DatabaseParameters = new HashSet<DatabaseParameter>();
        }
    
        public int EngineId { get; set; }
        public string Name { get; set; }

        [JsonIgnore]
        public virtual ICollection<DatabaseParameter> DatabaseParameters { get; set; }
    }
}
