//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationTool.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class FlatFilesParameter
    {
        public FlatFilesParameter()
        {
            this.Integrations = new HashSet<Integration>();
        }
    
        public int FlatFileParameterId { get; set; }
        public string Location { get; set; }

        [JsonIgnore]
        public virtual ICollection<Integration> Integrations { get; set; }
    }
}
