//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationTool.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Query
    {
        public Query()
        {
            this.Integrations = new HashSet<Integration>();
        }
    
        public int QueryId { get; set; }
        public string Query1 { get; set; }
        public string Description { get; set; }
        public int IntegrationTypeId { get; set; }
        public string QueryName { get; set; }

        [JsonIgnore]
        public virtual ICollection<Integration> Integrations { get; set; }
        public virtual IntegrationsType IntegrationsType { get; set; }
    }
}
