//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationTool.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Recurrence
    {
        public Recurrence()
        {
            this.Calendars = new HashSet<Calendar>();
        }
    
        public int RecurrenceId { get; set; }
        public string NameRecurrence { get; set; }

        [JsonIgnore]
        public virtual ICollection<Calendar> Calendars { get; set; }
    }
}
