//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemLog
    {
        public int SystemLogId { get; set; }
        public string Description { get; set; }
        public System.DateTime ErrorDate { get; set; }
        public int IntegrationId { get; set; }
    
        public virtual Integration Integration { get; set; }
    }
}
