//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationTool.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class UsersType
    {
        public UsersType()
        {
            this.Users = new HashSet<User>();
        }
    
        public int UserTypeId { get; set; }
        public string Type { get; set; }

        [JsonIgnore]
        public virtual ICollection<User> Users { get; set; }
    }
}
