//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationTool.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Integrations = new HashSet<Integration>();
            this.Permissions = new HashSet<Permission>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public int UserTypeId { get; set; }
        public int StatusId { get; set; }

        [JsonIgnore]
        public virtual ICollection<Integration> Integrations { get; set; }
        public virtual ICollection<Permission> Permissions { get; set; }
        public virtual Status Status { get; set; }
        public virtual UsersType UsersType { get; set; }
    }
}
