//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveDirectoryParameter
    {
        public int ActiveDirectoryId { get; set; }
        public string ADPath { get; set; }
        public string ADDomain { get; set; }
    }
}
